# Build Docker image for this app using Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker?view=vsts  
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'nodejssample:$(Build.BuildId)'
  # define two more variables dockerId and dockerPassword in the build pipeline in UI

steps:
- script: |
    sudo docker build -f Dockerfile -t $(dockerId)/$(imageName) .
    sudo docker login -u $(dockerId) -p $(dockerPassword)
    sudo docker push $(dockerId)/$(imageName)
    sudo docker run -t $(dockerId)/$(imageName)
  env:
    pswd: $(dockerPassword)
    
